package GUI;

import java.io.IOException;
import java.util.Random;

import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;

import Delegate.UserServiceDelegate;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import persistence.User;
import utils.Emailer;

public class ForgotPassController {
	@FXML
	private TextField mailid;
	@FXML
	private Button btnid;
	@FXML
	private Label label;
	@FXML
	private Label exit;
	public static final String ACCOUNT_SID = "AC36a7f2740a47bb4222b59ed9de2b153b";
    public static final String AUTH_TOKEN = "9231168e9ef8bb9d30194fe69aaf2f13";
	protected String getSaltString() {
     String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
     StringBuilder salt = new StringBuilder();
     Random rnd = new Random();
     while (salt.length() < 5) { // length of the random string.
         int index = (int) (rnd.nextFloat() * SALTCHARS.length());
         salt.append(SALTCHARS.charAt(index));
     }
     String saltStr = salt.toString();
     return saltStr;

 }
	 String y = getSaltString();

	Stage stage= new Stage();
    Scene scene;
	// Event Listener on Button[#btnid].onMouseClicked
	@FXML
	public void SendMail(MouseEvent event) throws IOException {
		 if (mailid.getText().isEmpty()){ label.setText("Enter your mail");  }
	        else if (!mailid.getText().matches("[a-zA-Z0-9\\.]+@[a-zA-Z0-9\\-\\_\\.]+\\.[a-zA-Z0-9]{2}") ){ label.setText("Mail not valid");  }
	        else{
	        	UserServiceDelegate UD=new UserServiceDelegate();
	        	User u=UD.findByMail(mailid.getText());
	        	 System.out.println(y);
	        	String mesg="Your code : " + y;
		
		Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

     Message messages = Message.creator(new PhoneNumber("+21695667688"),
     new PhoneNumber("+17083156678"), y).create();	
     Emailer um=new Emailer();
   um.SendEmail(mailid.getText(), "Password recovery", mesg);
		
		  FXMLLoader loader = new FXMLLoader(getClass().getResource("Code.fxml"));
          Parent root= loader.load();
          CodeController ccc = loader.getController();
          ccc.setEmail(mailid.getText());
          ccc.setCode(y);
          mailid.getScene().setRoot(root);
   }}
	// Event Listener on Label[#exit].onMouseClicked
	@FXML
	public void exit(MouseEvent event) {
		// TODO Autogenerated
	}
}
