package GUI;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class HomeController {
	@FXML
	private AnchorPane holderPane;
	@FXML
	private Button btnEspace;
	@FXML
	private Button btnInteraction;
	@FXML
	private Button btnForum;
	@FXML
	private Button btnProfile;
	@FXML
	private Button btnEvenement;

	// Event Listener on Button[#btnEspace].onAction
	@FXML
	public void switchEspace(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInteraction].onAction
	@FXML
	public void switchInteraction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnForum].onAction
	@FXML
	public void switchForum(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnProfile].onAction
	@FXML
	public void switchProfile(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEvenement].onAction
	@FXML
	public void switchEvenement(ActionEvent event) {
		// TODO Autogenerated
	}
}
